// <auto-generated />
namespace FantasyStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class image2355 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image2355));
        
        string IMigrationMetadata.Id
        {
            get { return "201505140142439_image2355"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
