// <auto-generated />
namespace FantasyStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cart2323ddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cart2323ddd));
        
        string IMigrationMetadata.Id
        {
            get { return "201505172302122_cart2323ddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
